Repository MolarVerse/PQ, pull requests merged in 2024-12, with the labels that each got.

#98 Documentation about Documentation
  docs/sphinx/src/developerGuide/developerGuide.rst
Labels: documentation

#97 Feature/dftb setup keyword
  CHANGELOG.md
  docs/sphinx/src/userGuide/inputFile.rst
  docs/sphinx/src/userGuide/setupFiles.rst
  include/config/defaults.hpp
  include/input/inputFileParser/filesInputParser.hpp
  include/settings/fileSettings.hpp
  src/QM/external/dftbplusRunner.cpp
  src/QM/scripts/dftbplus_periodic_stress
  src/input/inputFileParser/filesInputParser.cpp
  src/settings/fileSettings.cpp
  tests/data/dftbReader/dftb_in.template
  tests/data/inputFileReader/keywordList.txt
  tests/src/input/inputFileParsing/testFilesParser.cpp
Labels: documentation, enhancement

#101 Feature: keywords can now be given with '-' instead of '_' and vice versa
  include/utilities/stringUtilities.hpp
  src/input/inputFileParser/generalInputParser.cpp
  src/input/inputFileParser/inputFileParser.cpp
  src/input/inputFileParser/integratorInputParser.cpp
  src/input/inputFileParser/manostatInputParser.cpp
  src/input/inputFileParser/optInputParser.cpp
  src/input/inputFileParser/thermostatInputParser.cpp
  src/input/inputFileReader.cpp
  src/input/moldescriptorReader.cpp
  src/input/parameterFileReader/jCouplingSection.cpp
  src/input/parameterFileReader/parameterFileReader.cpp
  src/input/restartFileReader/restartFileReader.cpp
  src/input/topologyFileReader/jCouplingSection.cpp
  src/input/topologyFileReader/topologyReader.cpp
  src/settings/manostatSettings.cpp
  src/settings/optimizerSettings.cpp
  src/settings/potentialSettings.cpp
  src/settings/qmSettings.cpp
  src/settings/settings.cpp
  src/settings/thermostatSettings.cpp
  src/utilities/stringUtilities.cpp
  tests/src/input/parameterFileReader/testParameterFileReader.cpp
  tests/src/utilities/testStringUtilities.cpp
Labels: enhancement

#102 bugfix: processed invalid keyword gets printed
  src/input/inputFileReader.cpp
Labels: bug

#100 Feature: MACE example
  examples/acof1_mace/README.md
  examples/acof1_mace/acof1.rst
  examples/acof1_mace/moldescriptor.dat
  examples/acof1_mace/run-01.in
  examples/h2o_mace/README.md
  examples/h2o_mace/h2o.rst
  examples/h2o_mace/moldescriptor.dat
  examples/h2o_mace/run-01.in
Labels: enhancement
