Repository MolarVerse/PQ, pull requests merged in 2025-01, with the labels that each got.

#83 Tests: DFTBPlus integration
  .github/workflows/ci_debug.yml
  CHANGELOG.md
  CMakeLists.txt
  integration_tests/acof/acof1.rst
  integration_tests/acof/dftb_in.template
  integration_tests/acof/ref_data/acof1.rst
  integration_tests/acof/ref_data/band.out
  integration_tests/acof/ref_data/charges.bin
  integration_tests/acof/ref_data/coords.prev
  integration_tests/acof/ref_data/dftb.out.prev
  integration_tests/acof/ref_data/dftb_in.hsd
  integration_tests/acof/ref_data/dftb_in.template
  integration_tests/acof/ref_data/dftb_pin.hsd
  integration_tests/acof/ref_data/geom.gen
  integration_tests/acof/ref_data/md-01.box
  integration_tests/acof/ref_data/md-01.chrg
  integration_tests/acof/ref_data/md-01.en
  integration_tests/acof/ref_data/md-01.force
  integration_tests/acof/ref_data/md-01.info
  integration_tests/acof/ref_data/md-01.instant_en
  integration_tests/acof/ref_data/md-01.log
  integration_tests/acof/ref_data/md-01.log.ref
  integration_tests/acof/ref_data/md-01.mom
  integration_tests/acof/ref_data/md-01.rst
  integration_tests/acof/ref_data/md-01.stress
  integration_tests/acof/ref_data/md-01.timings
  integration_tests/acof/ref_data/md-01.vel
  integration_tests/acof/ref_data/md-01.vir
  integration_tests/acof/ref_data/md-01.xyz
  integration_tests/acof/ref_data/mm_forces
  integration_tests/acof/ref_data/qm_charges
  integration_tests/acof/ref_data/run-01.in
  integration_tests/acof/ref_data/run.out
  integration_tests/acof/run-01.in
  integration_tests/acof/slakos/3ob-3-1/C-C.skf
  integration_tests/acof/slakos/3ob-3-1/C-H.skf
  integration_tests/acof/slakos/3ob-3-1/C-N.skf
  integration_tests/acof/slakos/3ob-3-1/H-C.skf
  integration_tests/acof/slakos/3ob-3-1/H-H.skf
  integration_tests/acof/slakos/3ob-3-1/H-N.skf
  integration_tests/acof/slakos/3ob-3-1/N-C.skf
  integration_tests/acof/slakos/3ob-3-1/N-H.skf
  integration_tests/acof/slakos/3ob-3-1/N-N.skf
  integration_tests/acof/test_acof.py
  integration_tests/analysis.py
  src/engine/mdEngine.cpp
Labels: testing

#107 Decoupled the .ref file from the .log file
  CHANGELOG.md
  docs/sphinx/src/userGuide/inputFile.rst
  docs/sphinx/src/userGuide/outputFiles.rst
  include/config/defaults.hpp
  include/input/inputFileParser/outputInputParser.hpp
  include/settings/outputFileSettings.hpp
  src/input/inputFileParser/outputInputParser.cpp
  src/output/references/referencesOutput.cpp
  src/settings/outputFileSettings.cpp
  tests/data/inputFileReader/keywordList.txt
Labels: documentation, enhancement

#106 Documentation: Citations added for .ref output file
  .vscode/ltex.dictionary.en-US.txt
  CHANGELOG.md
  include/output/references/referenceFiles/berendsen.ref
  include/output/references/referenceFiles/berendsen.ref.bib
  include/output/references/referenceFiles/dftbplus.ref
  include/output/references/referenceFiles/dftbplus.ref.bib
  include/output/references/referenceFiles/langevin.ref
  include/output/references/referenceFiles/langevin.ref.bib
  include/output/references/referenceFiles/macemp.ref
  include/output/references/referenceFiles/macemp.ref.bib
  include/output/references/referenceFiles/maceoff.ref
  include/output/references/referenceFiles/maceoff.ref.bib
  include/output/references/referenceFiles/nose_hoover_chain.ref
  include/output/references/referenceFiles/nose_hoover_chain.ref.bib
  include/output/references/referenceFiles/pq.ref
  include/output/references/referenceFiles/pq.ref.bib
  include/output/references/referenceFiles/pyscf.ref
  include/output/references/referenceFiles/pyscf.ref.bib
  include/output/references/referenceFiles/rattle.ref
  include/output/references/referenceFiles/rattle.ref.bib
  include/output/references/referenceFiles/stochastic_rescaling.ref
  include/output/references/referenceFiles/stochastic_rescaling.ref.bib
  include/output/references/referenceFiles/turbomole.ref
  include/output/references/referenceFiles/turbomole.ref.bib
  include/output/references/referenceFiles/velocity_rescaling.ref
  include/output/references/referenceFiles/velocity_rescaling.ref.bib
  include/output/references/referenceFiles/velocity_verlet.ref
  include/output/references/referenceFiles/velocity_verlet.ref.bib
  include/output/references/references.hpp
  src/QM/scripts/turbomole_rimp2
  src/input/inputFileParser/QMInputParser.cpp
  src/input/inputFileParser/constraintsInputParser.cpp
  src/input/inputFileParser/integratorInputParser.cpp
  src/output/references/referencesOutput.cpp
Labels: bug, documentation, enhancement

#113 Added new ci workflow for checking PRs
  .github/workflows/pr_request.yml
  CHANGELOG.md
Labels: workflow

#99 Bugfix: Stochastic rescaling with Pade approximation
  CHANGELOG.md
  include/linearAlgebra/staticMatrix/staticMatrix3x3.hpp
  include/linearAlgebra/staticMatrix/staticMatrix3x3.tpp.hpp
  include/manostat/manostat.hpp
  src/manostat/berendsenManostat.cpp
  src/manostat/manostat.cpp
  src/manostat/stochasticRescalingManostat.cpp
  tests/src/linearAlgebra/testStaticMatrix3x3.cpp
  tests/src/manostat/testManostat.cpp
Labels: bug

#120 Feature: Compiling on macOS arm64
  .github/workflows/ci_debug.yml
  .github/workflows/ci_debug_macos.yml
  .github/workflows/ci_release.yml
  CHANGELOG.md
  CMakeLists.txt
Labels: workflow, compilation
